In [17]:
import numpy as np

#Permutations
import itertools as it

In [18]:
N = 3

#List up to N
#range(Start, Up to, Increment)
L = list(range(N))

L

[0, 1, 2]

In [19]:
#Generate permutations of L
for p in it.permutations(L):
 print(p)

(0, 1, 2)
(0, 2, 1)
(1, 0, 2)
(1, 2, 0)
(2, 0, 1)
(2, 1, 0)


In [20]:
N = 3

#Square matrix with N rows and N columns
M = np.arange(N**2).reshape((N,N))

M

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [22]:
#First Row
M[0]

#First Column, ":" means everything
M[:, 0]

#Second and Third rows
M[:, [2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [23]:
#M[Outer Dimension, Next Dimension]

M[1,2]


5

In [27]:
S = "Hello World"
# ":" Slices
#S[:4]
#S[2:7]

#Step
S[1:9:2]

'el o'

In [28]:
#Swap the rows
M[[2,1,0]]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [29]:
#Swap the columns
M[:, [1,2,0]]

array([[1, 2, 0],
       [4, 5, 3],
       [7, 8, 6]])