In [11]:
import numpy as np

a = np.arange(6)
a2 = a[np.newaxis, :]
a2.shape

a3 = np.arange(15).reshape(3,5)
a3

# the dimensions of the array. This is a tuple of integers 
# indicating the size of the array in each dimension. For a matrix with n rows 
# and m columns, shape will be (n,m). The length of the 
# shape tuple is therefore the number of axes, ndim.
a3.shape
# (3, 5)

# the number of axes (dimensions) of the array.
a3.ndim
# 2

# an object describing the type of the elements in the array
a3.dtype.name
# 'int32'

# the size in bytes of each element of the array
a3.itemsize
# 4

# Size of the array
a3.size
# 15

type(a3)
# numpy.ndarray

b = np.array([6,7,8])
b

type(b)
# numpy.ndarray

# transforms sequences of sequences into two-dimensional arrays
b2 = np.array([1.5,2,3]), ([4,5,6])
b2
# (array([1.5, 2. , 3. ]), [4, 5, 6]

# The type of the array can also be explicitly specified at creation time
c = np.array([1,2], dtype=complex)
c
# array([1.+0.j, 2.+0.j])

array([1.+0.j, 2.+0.j])